# Generated by Django 5.0.7 on 2024-09-11 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodmap',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Поставщик', null=True, on_delete=django.db.models.deletion.CASCADE, to='prod_chain.prodmap', verbose_name='поставщик'),
        ),
    ]
