# Generated by Django 5.0.7 on 2024-09-11 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_chain', '0002_alter_prodmap_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='town',
            field=models.CharField(db_index=True, help_text='Город контакта', max_length=254, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='prodmap',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Поставщик', null=True, on_delete=django.db.models.deletion.PROTECT, to='prod_chain.prodmap', verbose_name='поставщик'),
        ),
    ]
